<a href="https://colab.research.google.com/github/madinayergeshbay-sudo/2026_Spring_Application_Programming/blob/main/%EA%B3%BC%EC%A0%9C22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

quotes 크롤링 (1~10페이지)

In [1]:
import requests
from bs4 import BeautifulSoup

quotes_list = []

for page in range(1, 11):
    url = f"http://quotes.toscrape.com/page/{page}/"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    quotes = soup.select(".quote .text")

    for q in quotes:
        quotes_list.append(q.get_text())

print(len(quotes_list))
quotes_list[:5]

100

['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”',
 '“It is our choices, Harry, that show what we truly are, far more than our abilities.”',
 '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”',
 '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”',
 "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”"]

CountVectorizer 적용

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words='english')

X = vectorizer.fit_transform(quotes_list)

feature_names = vectorizer.get_feature_names_out()

. 가장 많이 나온 단어 TOP 5

In [3]:
import numpy as np

word_counts = X.sum(axis=0)
word_counts = np.array(word_counts).flatten()

top_indices = word_counts.argsort()[::-1][:5]

for i in top_indices:
    print(feature_names[i], word_counts[i])

love 23
think 12
life 12
make 10
don 9

0/1 Encoding 데이터프레임 만들기

In [4]:
import pandas as pd

binary_vectorizer = CountVectorizer(stop_words='english', binary=True)

X_binary = binary_vectorizer.fit_transform(quotes_list)

df = pd.DataFrame(X_binary.toarray(), columns=binary_vectorizer.get_feature_names_out())

df.head()

,000,10,abilities,absolutely,absurdities,accept,act,actually,admiration,admit,...,worth,worthy,wrap,write,writing,written,wrote,wrung,year,youer
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
import requests
from bs4 import BeautifulSoup

quotes_list = []

for page in range(1, 11):
    url = f"http://quotes.toscrape.com/page/{page}/"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    quotes = soup.find_all("span", class_="text")

    for q in quotes:
        quotes_list.append(q.get_text())

print(len(quotes_list))

100

In [6]:
import requests
from bs4 import BeautifulSoup

quotes_list = []
page = 1

while True:
    url = f"http://quotes.toscrape.com/page/{page}/"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    quotes = soup.find_all("span", class_="text")

    if not quotes:
        break

    for q in quotes:
        quotes_list.append(q.get_text())

    page += 1

print(len(quotes_list))

100

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(quotes_list)

df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())

df

,000,10,abilities,about,above,absolutely,absurdities,accept,across,act,...,writing,written,wrote,wrung,year,you,youer,your,yours,yourself
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,0,0,0,0
96,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,2,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0